from __future__ import annotations

import hashlib
import json
import numpy as np

from engine.tensor import Tensor, Parameter, zeros, ones, randn
from engine.module import Module
from engine.layers import Linear, Embedding
from config import DAHConfig


class AdapterLayer(Module):
    """Wraps a frozen Linear layer with a LoRA adapter.

    forward(x, A, B):
        base_out    = x @ W_base.T
        adapter_out = x @ B.T @ A.T * exp(log_scale)
        return base_out + adapter_out
    """

    def __init__(self, base_layer: Linear, rank: int, scale: float = 0.01):
        super().__init__()
        self.in_features = base_layer.in_features
        self.out_features = base_layer.out_features
        self.rank = rank

        # Freeze base weights as plain numpy (no Parameter, no grad)
        object.__setattr__(self, "base_weight_np", base_layer.weight.data.copy())
        if base_layer.bias is not None:
            object.__setattr__(self, "base_bias_np", base_layer.bias.data.copy())
        else:
            object.__setattr__(self, "base_bias_np", None)

        # log_scale is the single learnable scalar; exp(log_scale) recovers scale
        self.log_scale = Parameter(np.array([np.log(scale)]), name="log_scale")

    def forward(self, x: Tensor, A: Tensor | None = None,
                B: Tensor | None = None) -> Tensor:
        """
        x: (..., d_in)
        A: (d_out, r)
        B: (r, d_in)
        """
        W_t = Tensor(self.base_weight_np, requires_grad=False)
        # base_out: x @ W_base.T  — shape (..., d_out)
        base_out = x @ W_t.transpose()

        if self.base_bias_np is not None:
            b_t = Tensor(self.base_bias_np, requires_grad=False)
            base_out = base_out + b_t

        if A is not None and B is not None:
            # adapter: x @ B.T  -> (..., r), then @ A.T -> (..., d_out)
            xB = x @ B.transpose()          # (..., r)
            adapter_out = xB @ A.transpose()  # (..., d_out)
            # exp(log_scale) scalar
            scale_val = self.log_scale.exp()  # (1,)
            base_out = base_out + adapter_out * scale_val

        return base_out


class _MetaMLP(Module):
    """2-layer MLP: meta_dim -> meta_dim -> meta_dim with SiLU activation."""

    def __init__(self, meta_dim: int):
        super().__init__()
        self.fc1 = Linear(meta_dim, meta_dim)
        self.fc2 = Linear(meta_dim, meta_dim)

    def forward(self, x: Tensor) -> Tensor:
        return self.fc2(self.fc1(x).silu())


class DomainAdaptiveHypernetwork(Module):
    """One model, infinite domains via lightweight LoRA adapters generated by a hypernetwork."""

    def __init__(self, target_layers: dict[str, Linear], config: DAHConfig):
        super().__init__()
        self.config = config
        self.rank = config.adapter_rank
        self.meta_dim = config.meta_dim

        # Domain embedding table
        self.domain_embed = Embedding(config.n_domains, config.meta_dim)

        # Meta MLP: 2-layer
        self.meta_mlp = _MetaMLP(config.meta_dim)

        # Hypernetwork heads and adapter layer wrappers, keyed by layer name
        # We store them as plain dicts of Modules to avoid naming collisions.
        # Registration via object.__setattr__ with compound keys isn't clean;
        # instead we create sub-modules with sanitised attribute names.
        object.__setattr__(self, "_layer_names", list(target_layers.keys()))
        object.__setattr__(self, "_hyper_A", {})
        object.__setattr__(self, "_hyper_B", {})
        object.__setattr__(self, "_adapter_layers", {})
        object.__setattr__(self, "_domain_cache", {})
        object.__setattr__(self, "_current_domain", -1)
        object.__setattr__(self, "_domain_registry", {})   # name -> idx
        object.__setattr__(self, "_next_domain_idx", 0)
        # Optional rule encoder — set via attach_rule_encoder()
        object.__setattr__(self, "_rule_encoder", None)
        object.__setattr__(self, "_rule_registry", None)
        # Optional ontology embedding — set via attach_ontology_embedding()
        object.__setattr__(self, "_onto_embed", None)
        object.__setattr__(self, "_onto_registry", None)

        # OOD detection state (Mahalanobis distance in meta_mlp output space)
        object.__setattr__(self, "_seen_embeddings", {})   # domain_idx -> z_np (meta_dim,)
        object.__setattr__(self, "_ood_mean",     None)
        object.__setattr__(self, "_ood_inv_cov",  None)
        object.__setattr__(self, "_ood_threshold", None)
        object.__setattr__(self, "_ood_fitted",   False)

        for name, layer in target_layers.items():
            d_out = layer.out_features
            d_in = layer.in_features
            r = self.rank

            hyper_a = Linear(config.meta_dim, d_out * r)
            hyper_b = Linear(config.meta_dim, r * d_in)

            self._hyper_A[name] = hyper_a
            self._hyper_B[name] = hyper_b
            self._adapter_layers[name] = AdapterLayer(layer, r, config.adapter_scale)

            # Register as sub-modules so parameters() finds them
            safe = name.replace(".", "_")
            object.__getattribute__(self, "_modules")[f"hyper_A_{safe}"] = hyper_a
            object.__getattribute__(self, "_modules")[f"hyper_B_{safe}"] = hyper_b
            object.__getattribute__(self, "_modules")[f"adapter_{safe}"] = self._adapter_layers[name]

    # ------------------------------------------------------------------
    # Domain management
    # ------------------------------------------------------------------

    def register_domain(self, domain_name: str, metadata: dict) -> int:
        """Hash metadata to assign a stable domain index. Returns domain_idx."""
        registry = self._domain_registry
        if domain_name in registry:
            return registry[domain_name]

        # Derive a reproducible index from the metadata hash
        meta_str = json.dumps(metadata, sort_keys=True)
        h = int(hashlib.sha256(meta_str.encode()).hexdigest(), 16)
        idx = h % self.config.n_domains

        # Collision resolution: linear probing
        used = set(registry.values())
        while idx in used:
            idx = (idx + 1) % self.config.n_domains

        registry[domain_name] = idx
        object.__setattr__(self, "_domain_registry", registry)
        return idx

    def set_domain(self, domain_idx: int, warn_ood: bool = True):
        """
        Compute (or retrieve cached) adapters for domain_idx.

        warn_ood : if True and the OOD detector has been fitted, emits a
            RuntimeWarning when domain_idx lies outside the training convex
            hull.  The adapters are still generated — this is a warning, not
            a hard rejection.  Set warn_ood=False to silence in production
            if you have accepted this limitation explicitly.
        """
        if domain_idx == self._current_domain and domain_idx in self._domain_cache:
            return  # fast path

        if domain_idx not in self._domain_cache:
            adapters = self._compute_adapters(domain_idx)
            self._domain_cache[domain_idx] = adapters

        if warn_ood and self._ood_fitted:
            result = self.check_ood(domain_idx)
            if result["is_ood"]:
                import warnings
                warnings.warn(
                    f"DAH OOD: domain_idx={domain_idx} is outside the training "
                    f"distribution (Mahalanobis distance {result['distance']:.3f} > "
                    f"threshold {result['threshold']:.3f}, n_seen={result['n_seen']}). "
                    f"Adapter outputs may be unreliable.",
                    RuntimeWarning,
                    stacklevel=2,
                )

        object.__setattr__(self, "_current_domain", domain_idx)

    def _compute_adapters(self, domain_idx: int) -> dict[str, tuple[Tensor, Tensor]]:
        """Run hypernetwork for given domain_idx, return {name: (A, B)}."""
        idx_t = Tensor(np.array([domain_idx], dtype=np.int32), requires_grad=False)
        z = self.domain_embed(idx_t)            # (1, meta_dim)
        z = self.meta_mlp(z)                    # (1, meta_dim)

        # Rule-context injection: if a RuleEncoder + RuleRegistry are attached,
        # add the domain's rule embedding to z so adapters become rule-aware.
        # This is additive — zero-padded domains see no effect.
        if self._rule_encoder is not None and self._rule_registry is not None:
            enc = self._rule_registry.encode_domain(domain_idx)   # (max_rules, rule_dim) numpy
            z_rule = self._rule_encoder.forward(enc)               # (1, meta_dim) Tensor
            z_data = z.data + z_rule.data                          # broadcast add
            z = Tensor(z_data, requires_grad=z.requires_grad,
                       _children=(z, z_rule), _op="rule_inject")

            _z_orig, _z_rule = z._prev

            def _rule_inject_back():
                if z.grad is None:
                    return
                if _z_orig.requires_grad:
                    _z_orig.grad = (_z_orig.grad + z.grad
                                    if _z_orig.grad is not None else z.grad.copy())
                if _z_rule.requires_grad:
                    _z_rule.grad = (_z_rule.grad + z.grad
                                    if _z_rule.grad is not None else z.grad.copy())

            z._backward = _rule_inject_back

        # Ontology context injection: if an OntologyEmbedding + OntologyRegistry
        # are attached, add the domain's ontology vector to z.
        if self._onto_embed is not None and self._onto_registry is not None:
            z_onto = self._onto_registry.encode_domain_vec(
                self._onto_embed, domain_idx
            )                                                # (1, meta_dim) Tensor
            z_data = z.data + z_onto.data
            z = Tensor(z_data, requires_grad=z.requires_grad,
                       _children=(z, z_onto), _op="onto_inject")

            _z_base, _z_onto = z._prev

            def _onto_inject_back():
                if z.grad is None:
                    return
                if _z_base.requires_grad:
                    _z_base.grad = (_z_base.grad + z.grad
                                    if _z_base.grad is not None else z.grad.copy())
                if _z_onto.requires_grad:
                    _z_onto.grad = (_z_onto.grad + z.grad
                                    if _z_onto.grad is not None else z.grad.copy())

            z._backward = _onto_inject_back

        # Record embedding for OOD calibration (invalidate fit on new domain)
        seen = dict(self._seen_embeddings)
        seen[domain_idx] = z.data[0].copy()
        object.__setattr__(self, "_seen_embeddings", seen)
        object.__setattr__(self, "_ood_fitted", False)

        result = {}
        for name in self._layer_names:
            hyper_a = self._hyper_A[name]
            hyper_b = self._hyper_B[name]

            layer = self._adapter_layers[name]
            d_out = layer.out_features
            d_in = layer.in_features
            r = self.rank

            A_flat = hyper_a(z)                 # (1, d_out * r)
            B_flat = hyper_b(z)                 # (1, r * d_in)

            A = A_flat.reshape(d_out, r)         # (d_out, r)
            B = B_flat.reshape(r, d_in)          # (r, d_in)

            result[name] = (A, B)

        return result

    def attach_ontology_embedding(self, embed, registry) -> None:
        """
        Wire an OntologyEmbedding + OntologyRegistry into DAH.

        After this call, every `_compute_adapters` run will add the domain's
        ontology context vector to z, making adapters semantic-sensor-aware.

        Parameters
        ----------
        embed    : OntologyEmbedding instance (meta_dim must match DAHConfig.meta_dim)
        registry : OntologyRegistry with an `encode_domain_vec(embed, domain_idx)`
                   convenience method (see OntologyRegistry.encode_domain_vec)
        """
        object.__setattr__(self, "_onto_embed", embed)
        object.__setattr__(self, "_onto_registry", registry)
        self.clear_cache()

    def attach_rule_encoder(self, encoder, registry) -> None:
        """
        Wire a RuleEncoder + RuleRegistry into DAH.

        After this call, every `_compute_adapters` run will add the domain's
        rule context vector to the meta_mlp output z, so the hypernetwork
        generates rule-aware adapter weights.

        Parameters
        ----------
        encoder  : RuleEncoder instance (meta_dim must match DAHConfig.meta_dim)
        registry : RuleRegistry instance populated with per-domain rules
        """
        object.__setattr__(self, "_rule_encoder", encoder)
        object.__setattr__(self, "_rule_registry", registry)
        self.clear_cache()   # invalidate old adapters

    def clear_cache(self):
        """Clear adapter cache so hypernetwork is recomputed on next set_domain call."""
        object.__setattr__(self, "_domain_cache", {})
        object.__setattr__(self, "_current_domain", -1)

    # ------------------------------------------------------------------
    # OOD detection
    # ------------------------------------------------------------------

    def fit_ood_detector(self, threshold_percentile: float = 95.0) -> bool:
        """
        Fit a Mahalanobis-distance OOD detector on all domain embeddings seen
        so far (i.e., the convex hull of training-time domains).

        Call this once after training / after registering all known domains.
        Returns True if the fit succeeded (requires >= 4 seen domains).

        threshold_percentile : distance percentile of seen embeddings used as
            the OOD boundary.  95 means 5% of training domains will be flagged
            as borderline; increase to 99 for a looser boundary.
        """
        seen = self._seen_embeddings
        if len(seen) < 4:
            return False

        Z = np.stack(list(seen.values()), axis=0)   # (n, meta_dim)
        mean = Z.mean(axis=0)
        # Ridge-regularised covariance so inv is stable even with few domains
        cov = np.cov(Z.T) + 1e-4 * np.eye(Z.shape[1])
        try:
            inv_cov = np.linalg.inv(cov)
        except np.linalg.LinAlgError:
            inv_cov = np.linalg.pinv(cov)

        # Calibrate threshold from seen embeddings' own distances
        diffs = Z - mean                                             # (n, d)
        dists = np.sqrt(np.einsum("nd,dd,nd->n", diffs, inv_cov, diffs))
        threshold = float(np.percentile(dists, threshold_percentile))

        object.__setattr__(self, "_ood_mean",     mean)
        object.__setattr__(self, "_ood_inv_cov",  inv_cov)
        object.__setattr__(self, "_ood_threshold", threshold)
        object.__setattr__(self, "_ood_fitted",   True)
        return True

    def check_ood(self, domain_idx: int) -> dict:
        """
        Check whether `domain_idx` falls outside the training distribution.

        Lazily fits the detector on first call if not already fitted.

        Returns
        -------
        dict with keys:
          is_ood    : bool   — True if distance > fitted threshold
          distance  : float  — Mahalanobis distance in meta_mlp output space
          threshold : float  — fitted boundary (0.0 if detector not ready)
          n_seen    : int    — number of domains used to fit the detector
        """
        if not self._ood_fitted:
            self.fit_ood_detector()

        n_seen = len(self._seen_embeddings)
        if not self._ood_fitted:
            # Not enough data yet — conservative: do not flag
            return {"is_ood": False, "distance": 0.0,
                    "threshold": 0.0, "n_seen": n_seen}

        # Get embedding: use cached version or compute fresh
        if domain_idx in self._seen_embeddings:
            z_np = self._seen_embeddings[domain_idx]
        else:
            idx_t = Tensor(np.array([domain_idx], dtype=np.int32), requires_grad=False)
            z = self.meta_mlp(self.domain_embed(idx_t))
            z_np = z.data[0]

        diff = z_np - self._ood_mean
        dist = float(np.sqrt(diff @ self._ood_inv_cov @ diff))
        threshold = float(self._ood_threshold)

        return {
            "is_ood":    dist > threshold,
            "distance":  dist,
            "threshold": threshold,
            "n_seen":    n_seen,
        }

    def get_adapters(self, domain_idx: int) -> dict[str, tuple[Tensor, Tensor]]:
        """Return {layer_name: (A, B)} for all target layers."""
        if domain_idx not in self._domain_cache:
            adapters = self._compute_adapters(domain_idx)
            self._domain_cache[domain_idx] = adapters
        return self._domain_cache[domain_idx]

    def forward(self, x: Tensor, layer_name: str, domain_idx: int = 0) -> Tensor:
        """Route x through the adapter-injected layer for given domain."""
        self.set_domain(domain_idx)
        adapters = self._domain_cache[domain_idx]
        A, B = adapters[layer_name]
        return self._adapter_layers[layer_name](x, A, B)

    def adapter_params_count(self) -> int:
        """Count only adapter parameters (not frozen base weights)."""
        total = 0
        # Hypernetwork params
        for hyper in self._hyper_A.values():
            total += hyper.n_params()
        for hyper in self._hyper_B.values():
            total += hyper.n_params()
        # log_scale per adapter layer
        for adapter in self._adapter_layers.values():
            total += 1  # log_scale is shape (1,)
        # domain_embed + meta_mlp
        total += self.domain_embed.n_params()
        total += self.meta_mlp.n_params()
        return total
