import hashlib
import json
import numpy as np
from typing import Dict, List, Optional, Tuple

from engine.tensor import Tensor, Parameter, zeros, ones, randn
from engine.module import Module
from engine.layers import Linear, Embedding
from config import DAHConfig


class AdapterLayer(Module):
    """Wraps a frozen Linear layer with a LoRA adapter.

    forward(x, A, B):
        base_out    = x @ W_base.T
        adapter_out = x @ B.T @ A.T * exp(log_scale)
        return base_out + adapter_out
    """

    def __init__(self, base_layer: Linear, rank: int, scale: float = 0.01):
        super().__init__()
        self.in_features = base_layer.in_features
        self.out_features = base_layer.out_features
        self.rank = rank

        # Freeze base weights as plain numpy (no Parameter, no grad)
        object.__setattr__(self, "base_weight_np", base_layer.weight.data.copy())
        if base_layer.bias is not None:
            object.__setattr__(self, "base_bias_np", base_layer.bias.data.copy())
        else:
            object.__setattr__(self, "base_bias_np", None)

        # log_scale is the single learnable scalar; exp(log_scale) recovers scale
        self.log_scale = Parameter(np.array([np.log(scale)]), name="log_scale")

    def forward(self, x: Tensor, A: Optional[Tensor] = None,
                B: Optional[Tensor] = None) -> Tensor:
        """
        x: (..., d_in)
        A: (d_out, r)
        B: (r, d_in)
        """
        W_t = Tensor(self.base_weight_np, requires_grad=False)
        # base_out: x @ W_base.T  — shape (..., d_out)
        base_out = x @ W_t.transpose()

        if self.base_bias_np is not None:
            b_t = Tensor(self.base_bias_np, requires_grad=False)
            base_out = base_out + b_t

        if A is not None and B is not None:
            # adapter: x @ B.T  -> (..., r), then @ A.T -> (..., d_out)
            xB = x @ B.transpose()          # (..., r)
            adapter_out = xB @ A.transpose()  # (..., d_out)
            # exp(log_scale) scalar
            scale_val = self.log_scale.exp()  # (1,)
            base_out = base_out + adapter_out * scale_val

        return base_out


class _MetaMLP(Module):
    """2-layer MLP: meta_dim -> meta_dim -> meta_dim with SiLU activation."""

    def __init__(self, meta_dim: int):
        super().__init__()
        self.fc1 = Linear(meta_dim, meta_dim)
        self.fc2 = Linear(meta_dim, meta_dim)

    def forward(self, x: Tensor) -> Tensor:
        return self.fc2(self.fc1(x).silu())


class DomainAdaptiveHypernetwork(Module):
    """One model, infinite domains via lightweight LoRA adapters generated by a hypernetwork."""

    def __init__(self, target_layers: Dict[str, Linear], config: DAHConfig):
        super().__init__()
        self.config = config
        self.rank = config.adapter_rank
        self.meta_dim = config.meta_dim

        # Domain embedding table
        self.domain_embed = Embedding(config.n_domains, config.meta_dim)

        # Meta MLP: 2-layer
        self.meta_mlp = _MetaMLP(config.meta_dim)

        # Hypernetwork heads and adapter layer wrappers, keyed by layer name
        # We store them as plain dicts of Modules to avoid naming collisions.
        # Registration via object.__setattr__ with compound keys isn't clean;
        # instead we create sub-modules with sanitised attribute names.
        object.__setattr__(self, "_layer_names", list(target_layers.keys()))
        object.__setattr__(self, "_hyper_A", {})
        object.__setattr__(self, "_hyper_B", {})
        object.__setattr__(self, "_adapter_layers", {})
        object.__setattr__(self, "_domain_cache", {})
        object.__setattr__(self, "_current_domain", -1)
        object.__setattr__(self, "_domain_registry", {})   # name -> idx
        object.__setattr__(self, "_next_domain_idx", 0)

        for name, layer in target_layers.items():
            d_out = layer.out_features
            d_in = layer.in_features
            r = self.rank

            hyper_a = Linear(config.meta_dim, d_out * r)
            hyper_b = Linear(config.meta_dim, r * d_in)

            self._hyper_A[name] = hyper_a
            self._hyper_B[name] = hyper_b
            self._adapter_layers[name] = AdapterLayer(layer, r, config.adapter_scale)

            # Register as sub-modules so parameters() finds them
            safe = name.replace(".", "_")
            object.__getattribute__(self, "_modules")[f"hyper_A_{safe}"] = hyper_a
            object.__getattribute__(self, "_modules")[f"hyper_B_{safe}"] = hyper_b
            object.__getattribute__(self, "_modules")[f"adapter_{safe}"] = self._adapter_layers[name]

    # ------------------------------------------------------------------
    # Domain management
    # ------------------------------------------------------------------

    def register_domain(self, domain_name: str, metadata: dict) -> int:
        """Hash metadata to assign a stable domain index. Returns domain_idx."""
        registry = self._domain_registry
        if domain_name in registry:
            return registry[domain_name]

        # Derive a reproducible index from the metadata hash
        meta_str = json.dumps(metadata, sort_keys=True)
        h = int(hashlib.sha256(meta_str.encode()).hexdigest(), 16)
        idx = h % self.config.n_domains

        # Collision resolution: linear probing
        used = set(registry.values())
        while idx in used:
            idx = (idx + 1) % self.config.n_domains

        registry[domain_name] = idx
        object.__setattr__(self, "_domain_registry", registry)
        return idx

    def set_domain(self, domain_idx: int):
        """Compute (or retrieve cached) adapters for domain_idx."""
        if domain_idx == self._current_domain and domain_idx in self._domain_cache:
            return  # fast path

        if domain_idx not in self._domain_cache:
            adapters = self._compute_adapters(domain_idx)
            self._domain_cache[domain_idx] = adapters

        object.__setattr__(self, "_current_domain", domain_idx)

    def _compute_adapters(self, domain_idx: int) -> Dict[str, Tuple[Tensor, Tensor]]:
        """Run hypernetwork for given domain_idx, return {name: (A, B)}."""
        idx_t = Tensor(np.array([domain_idx], dtype=np.int32), requires_grad=False)
        z = self.domain_embed(idx_t)            # (1, meta_dim)
        z = self.meta_mlp(z)                    # (1, meta_dim)

        result = {}
        for name in self._layer_names:
            hyper_a = self._hyper_A[name]
            hyper_b = self._hyper_B[name]

            layer = self._adapter_layers[name]
            d_out = layer.out_features
            d_in = layer.in_features
            r = self.rank

            A_flat = hyper_a(z)                 # (1, d_out * r)
            B_flat = hyper_b(z)                 # (1, r * d_in)

            A = A_flat.reshape(d_out, r)         # (d_out, r)
            B = B_flat.reshape(r, d_in)          # (r, d_in)

            result[name] = (A, B)

        return result

    def clear_cache(self):
        """Clear adapter cache so hypernetwork is recomputed on next set_domain call."""
        object.__setattr__(self, "_domain_cache", {})
        object.__setattr__(self, "_current_domain", -1)

    def get_adapters(self, domain_idx: int) -> Dict[str, Tuple[Tensor, Tensor]]:
        """Return {layer_name: (A, B)} for all target layers."""
        if domain_idx not in self._domain_cache:
            adapters = self._compute_adapters(domain_idx)
            self._domain_cache[domain_idx] = adapters
        return self._domain_cache[domain_idx]

    def forward(self, x: Tensor, layer_name: str, domain_idx: int = 0) -> Tensor:
        """Route x through the adapter-injected layer for given domain."""
        self.set_domain(domain_idx)
        adapters = self._domain_cache[domain_idx]
        A, B = adapters[layer_name]
        return self._adapter_layers[layer_name](x, A, B)

    def adapter_params_count(self) -> int:
        """Count only adapter parameters (not frozen base weights)."""
        total = 0
        # Hypernetwork params
        for hyper in self._hyper_A.values():
            total += hyper.n_params()
        for hyper in self._hyper_B.values():
            total += hyper.n_params()
        # log_scale per adapter layer
        for adapter in self._adapter_layers.values():
            total += 1  # log_scale is shape (1,)
        # domain_embed + meta_mlp
        total += self.domain_embed.n_params()
        total += self.meta_mlp.n_params()
        return total
